"""
Containing all declared strings

"""

CONFIG_HEADER_ACCOUNT = "ACCOUNT"
CONFIG_HEADER_BROKER = "BROKER"
CONFIG_HEADER_STOCKS = "STOCKS"
CONFIG_HEADER_STRATEGIES = "STRATEGIES"
CONFIG_HEADER_STOPS = "STOPS"

STOP_TYPE_STOP_LOSS = "STOP_LOSS"
STOP_TYPE_TRAILING_STOP = "TRAILING_STOP"


JSON_WORKFLOW_FOLDER_STRUCTURE_SUMMARY = "workflow_summary.json"